import 'package:forui/forui.dart';
import 'package:flutter/material.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get neutralLight {
  // Change this to false to generate a desktop variant of the theme.
  const touch = true;

  const colors = FColors(
    brightness: .light,
    systemOverlayStyle: .dark,
    barrier: Color(0x33000000),
    background: Color(0xFFF5F7FB),
    foreground: Color(0xFF14213D),
    primary: Color(0xFF3157D5),
    primaryForeground: Color(0xFFFFFFFF),
    secondary: Color(0xFFE8EEFF),
    secondaryForeground: Color(0xFF2447B8),
    muted: Color(0xFFEEF2F7),
    mutedForeground: Color(0xFF667085),
    destructive: Color(0xFFD92D20),
    destructiveForeground: Color(0xFFFFFFFF),
    error: Color(0xFFD92D20),
    errorForeground: Color(0xFFFFFFFF),
    card: Color(0xFFFFFFFF),
    border: Color(0xFFD6DDEA),
  );

  final typography = _typography(colors: colors, touch: touch);
  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  );
}

FThemeData get neutralDark {
  // Change this to false to generate a desktop variant of the theme.
  const touch = true;

  const colors = FColors(
    brightness: .dark,
    systemOverlayStyle: .light,
    barrier: Color(0x7A000000),
    background: Color(0xFF0D1321),
    foreground: Color(0xFFF4F7FB),
    primary: Color(0xFF8CA6FF),
    primaryForeground: Color(0xFF0B1533),
    secondary: Color(0xFF1B2948),
    secondaryForeground: Color(0xFFDDE6FF),
    muted: Color(0xFF172033),
    mutedForeground: Color(0xFF98A5BA),
    destructive: Color(0xFFFF6B6B),
    destructiveForeground: Color(0xFF1C0A0A),
    error: Color(0xFFFF6B6B),
    errorForeground: Color(0xFF1C0A0A),
    card: Color(0xFF121B2E),
    border: Color(0xFF2A3750),
  );

  final typography = _typography(colors: colors, touch: touch);
  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  );
}

FTypography _typography({
  required FColors colors,
  required bool touch,
  String fontFamily = FTypography.defaultFontFamily,
}) {
  assert(
    fontFamily.isNotEmpty,
    'fontFamily ($fontFamily) should not be empty.',
  );
  final color = colors.foreground;
  final font = fontFamily;
  if (touch) {
    return FTypography(
      fontFamily: fontFamily,
      xs3: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 10,
        height: 1,
        leadingDistribution: .even,
      ),
      xs2: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 12,
        height: 1,
        leadingDistribution: .even,
      ),
      xs: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 14,
        height: 1.25,
        leadingDistribution: .even,
      ),
      sm: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 16,
        height: 1.5,
        leadingDistribution: .even,
      ),
      md: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 18,
        height: 1.75,
        leadingDistribution: .even,
      ),
      lg: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 20,
        height: 1.75,
        leadingDistribution: .even,
      ),
      xl: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 22,
        height: 2,
        leadingDistribution: .even,
      ),
      xl2: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 30,
        height: 2.25,
        leadingDistribution: .even,
      ),
      xl3: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 36,
        height: 2.5,
        leadingDistribution: .even,
      ),
      xl4: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 48,
        height: 1,
        leadingDistribution: .even,
      ),
      xl5: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 60,
        height: 1,
        leadingDistribution: .even,
      ),
      xl6: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 72,
        height: 1,
        leadingDistribution: .even,
      ),
      xl7: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 96,
        height: 1,
        leadingDistribution: .even,
      ),
      xl8: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 108,
        height: 1,
        leadingDistribution: .even,
      ),
    );
  } else {
    return FTypography(
      fontFamily: fontFamily,
      xs3: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 8,
        height: 1,
        leadingDistribution: .even,
      ),
      xs2: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 10,
        height: 1,
        leadingDistribution: .even,
      ),
      xs: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 12,
        height: 1,
        leadingDistribution: .even,
      ),
      sm: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 14,
        height: 1.25,
        leadingDistribution: .even,
      ),
      md: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 16,
        height: 1.5,
        leadingDistribution: .even,
      ),
      lg: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 18,
        height: 1.75,
        leadingDistribution: .even,
      ),
      xl: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 20,
        height: 1.75,
        leadingDistribution: .even,
      ),
      xl2: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 22,
        height: 2,
        leadingDistribution: .even,
      ),
      xl3: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 30,
        height: 2.25,
        leadingDistribution: .even,
      ),
      xl4: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 36,
        height: 2.5,
        leadingDistribution: .even,
      ),
      xl5: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 48,
        height: 1,
        leadingDistribution: .even,
      ),
      xl6: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 60,
        height: 1,
        leadingDistribution: .even,
      ),
      xl7: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 72,
        height: 1,
        leadingDistribution: .even,
      ),
      xl8: TextStyle(
        color: color,
        fontFamily: font,
        fontSize: 96,
        height: 1,
        leadingDistribution: .even,
      ),
    );
  }
}

FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  const borderRadius = FBorderRadius();
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    hapticFeedback: const FHapticFeedback(),
    borderRadius: const FBorderRadius(),
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [],
  );
}
